# Generated by Django 4.1.2 on 2024-07-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidaSaludable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetal_favorito', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('ejercicio_favorito', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='datos',
            name='peso',
            field=models.FloatField(default=60),
            preserve_default=False,
        ),
    ]
