# Generated by Django 4.1.2 on 2025-10-17 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0002_vidasaludable_datos_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='perfil',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('estudiante', 'Estudiante')], default='estudiante', max_length=15),
        ),
        migrations.AddField(
            model_name='datos',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
