# Generated by Django 4.1.2 on 2025-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_datos_perfil_datos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='perfil',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('estudiante', 'Estudiante')], default='estudiante', max_length=15, null=True),
        ),
    ]
